#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

# Do not modify this file by hand!  Run ./update-setup.py instead.

from distutils.core import setup

packages = \
['importlib_resources',
 'importlib_resources.tests',
 'importlib_resources.tests.data01',
 'importlib_resources.tests.data01.subdirectory',
 'importlib_resources.tests.zipdata01']

package_data = \
{'': ['*'], 'importlib_resources': ['docs/*', 'docs/_static/*']}

extras_require = \
{":python_version < '3'": ['pathlib2'], ":python_version < '3.5'": ['typing']}

setup(name='importlib_resources',
      version='0.2',
      description='Read resources contained within a package.',
      author='Brett Cannon\nBarry Warsaw',
      author_email='brett@python.org\nbarry@python.org',
      url='http://importlib-resources.readthedocs.io/',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='==2.7,>=3.4',
     )
